print(format('SRINU MK STORES','>30'))
print(format('near sri nagar coloy','>32'))
print("\t   ************************")
a=input(" product name:\t")
b=input("product price:\t")
print("\t \t------------------")
print("  total amout :\t",b)